### PR TITLE
HTTPS

### PR DESCRIPTION
**Pull request by janyksteenbeek**
Using HTTPS endpoint for Yo API.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This shouldn't have been merged. This repo is meant to be READ ONLY.

**Comment by jbrooksuk** [comment]
When did this change?

**Comment by GrahamCampbell** [comment]
Today.

**Comment by GrahamCampbell** [comment]
https://github.com/notifymehq/notifyme

**Comment by GrahamCampbell** [comment]
I let you all know the plan earlier today in slack.

**Comment by jbrooksuk** [comment]
Damn it, no notifications. My bad.

**Comment by GrahamCampbell** [comment]
This PR is getting reverted via a hard reset.

**Comment by jbrooksuk** [comment]
:+1:

**Pull request merged**
